# Generated by Django 4.0 on 2022-01-08 01:44

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Tenant User',
                'verbose_name_plural': 'Tenants User',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
