# Generated by Django 4.0 on 2022-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Texto')),
                ('checkbox', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Minha Lista',
                'verbose_name_plural': 'Minhas Listas',
            },
        ),
    ]
